name: multidgd-paper

channels:
  - conda-forge
  - pytorch

dependencies: # there are many more dependencies but it was not possible to install on osx in one go, more in env.sh
  - python==3.9.6
  - ipython==8.14.0
  - matplotlib==3.7.1
  - numpy==1.24.3
  - pandas==1.5.3
  - pytorch==2.0.1
  - tqdm==4.65.0
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - seaborn==0.12.2
  - umap-learn==0.5.3